#!/usr/bin/env bash
#w
awk '
{
  count[$1, $9]++
}
END {
  for (key in count) {
    print count[key], key
  }
}
' access.log | \
awk '
{
  split($2, a, SUBSEP)
  print $1, a[1], a[2]
}
' | sort -nr



