#!/usr/bin/env bash
#w
PID_FILE=/var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f "$PID_FILE"; exit 0' SIGTERM

trap 'echo "Y U no love me?!"; exit 0' SIGINT

trap 'rm -f "$PID_FILE"; exit 0' SIGQUIT


echo $$ > "$PID_FILE" || { echo "Error creating PID file" >&2; exit 1; }


while true; do

  echo "To infinity and beyond"

  sleep 1

done
