#!/usr/bin/env bash
#w
pkill -f '4-to_infinity_and_beyond'

# Print the required output
for i in {1..10}
do
    echo "To infinity and beyond"
    # Use i to avoid the warning
    : "$i"
done

echo "Terminated."
