#!/usr/bin/env bash
# Find the process ID of 7-highlander
trap 'echo "I am invincible!!!"' TERM


# Loop indefinitely, printing the message and sleeping.

while true; do

  echo "To infinity and beyond"

  sleep 2

done
